project:
  type: book

book:
  title: "Ecologia de Paisagens com R"
  author: "Darren Norris"
  date: "5/03/2023"
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - part: escala-met.qmd
      chapters:
      - escala.qmd
      - metricas.qmd
    - part: codigo-R.qmd
      chapters:
        - codigo-livro.qmd
        - codigo-raster.qmd
        - codigo-vector.qmd
    - references.qmd
  cover-image: cover.png

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
lang: pt-BR
language:
  label:
    fig: "Figura "
    tab: "Tabela "
  ui:
    chapter_name: "Capítulo "