<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Respostas multiescala de espécies | Ecologia de Paisagens com R</title>
  <meta name="description" content="This is a minimal example." />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Respostas multiescala de espécies | Ecologia de Paisagens com R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://darrennorris.github.io/epr/pref%C3%A1cio-%C3%A0-primeira-edi%C3%A7%C3%A3o.html//cover.jpg" />
  <meta property="og:description" content="This is a minimal example." />
  <meta name="github-repo" content="darrennorris/epr" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Respostas multiescala de espécies | Ecologia de Paisagens com R" />
  
  <meta name="twitter:description" content="This is a minimal example." />
  <meta name="twitter:image" content="https://darrennorris.github.io/epr/pref%C3%A1cio-%C3%A0-primeira-edi%C3%A7%C3%A3o.html//cover.jpg" />

<meta name="author" content="Darren Norris: darren.norris@unifap.br" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cap02.html"/>
<link rel="next" href="garimpo-do-lourenço.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">epr</a></li>

<li class="divider"></li>
<li class="part"><span><b>I Apresentação</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bem-vindos</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#agradecimentos"><i class="fa fa-check"></i>Agradecimentos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="prefácio-à-primeira-edição.html"><a href="prefácio-à-primeira-edição.html"><i class="fa fa-check"></i>Prefácio à primeira edição</a></li>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html"><i class="fa fa-check"></i>Introdução</a>
<ul>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#o-que-você-vai-aprender"><i class="fa fa-check"></i>O que você vai aprender</a></li>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#como-este-livro-está-organizado"><i class="fa fa-check"></i>Como este livro está organizado</a></li>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#o-que-você-não-vai-aprender"><i class="fa fa-check"></i>O que você não vai aprender</a></li>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a>
<ul>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#rstudio"><i class="fa fa-check"></i>RStudio</a></li>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#o-universo-arrumado---tidyverse"><i class="fa fa-check"></i>O universo arrumado - tidyverse</a></li>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#outros-pacotes"><i class="fa fa-check"></i>Outros pacotes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#codigo-no-livro"><i class="fa fa-check"></i>Codigo no livro</a>
<ul>
<li class="chapter" data-level="" data-path="introdução.html"><a href="introdução.html#organização-do-codigo-no-livro"><i class="fa fa-check"></i>Organização do codigo no livro</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Escala e padrões</b></span></li>
<li class="chapter" data-level="1" data-path="cap01.html"><a href="cap01.html"><i class="fa fa-check"></i><b>1</b> Escala</a>
<ul>
<li class="chapter" data-level="1.1" data-path="cap01.html"><a href="cap01.html#apresentação"><i class="fa fa-check"></i><b>1.1</b> Apresentação</a></li>
<li class="chapter" data-level="1.2" data-path="cap01.html"><a href="cap01.html#escala-breve-definação"><i class="fa fa-check"></i><b>1.2</b> Escala: breve definação</a></li>
<li class="chapter" data-level="1.3" data-path="cap01.html"><a href="cap01.html#pacotes-e-dados"><i class="fa fa-check"></i><b>1.3</b> Pacotes e dados</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="cap01.html"><a href="cap01.html#pacotes"><i class="fa fa-check"></i><b>1.3.1</b> Pacotes</a></li>
<li class="chapter" data-level="1.3.2" data-path="cap01.html"><a href="cap01.html#dados"><i class="fa fa-check"></i><b>1.3.2</b> Dados</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="cap01.html"><a href="cap01.html#alterando-a-resolução"><i class="fa fa-check"></i><b>1.4</b> Alterando a resolução</a></li>
<li class="chapter" data-level="1.5" data-path="cap01.html"><a href="cap01.html#escala-espacial-e-desenho-amostral"><i class="fa fa-check"></i><b>1.5</b> Escala espacial e desenho amostral</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="cap01.html"><a href="cap01.html#obter-e-carregar-dados-vectores"><i class="fa fa-check"></i><b>1.5.1</b> Obter e carregar dados (vectores)</a></li>
<li class="chapter" data-level="1.5.2" data-path="cap01.html"><a href="cap01.html#visualizar-os-arquivos-camadas-vector"><i class="fa fa-check"></i><b>1.5.2</b> Visualizar os arquivos (camadas vector)</a></li>
<li class="chapter" data-level="1.5.3" data-path="cap01.html"><a href="cap01.html#obter-e-carregar-dados-raster"><i class="fa fa-check"></i><b>1.5.3</b> Obter e carregar dados (raster)</a></li>
<li class="chapter" data-level="1.5.4" data-path="cap01.html"><a href="cap01.html#visualizar-os-arquivos-camadas-raster-e-vector"><i class="fa fa-check"></i><b>1.5.4</b> Visualizar os arquivos (camadas raster e vector)</a></li>
<li class="chapter" data-level="1.5.5" data-path="cap01.html"><a href="cap01.html#reclassificação"><i class="fa fa-check"></i><b>1.5.5</b> Reclassificação</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="cap01.html"><a href="cap01.html#comparação-multiescala"><i class="fa fa-check"></i><b>1.6</b> Comparação multiescala</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="cap01.html"><a href="cap01.html#pergunta-4"><i class="fa fa-check"></i><b>1.6.1</b> Pergunta 4</a></li>
<li class="chapter" data-level="1.6.2" data-path="cap01.html"><a href="cap01.html#pergunta-5"><i class="fa fa-check"></i><b>1.6.2</b> Pergunta 5</a></li>
<li class="chapter" data-level="1.6.3" data-path="cap01.html"><a href="cap01.html#pergunta-6"><i class="fa fa-check"></i><b>1.6.3</b> Pergunta 6</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="cap01.html"><a href="cap01.html#próximos-passos-repetindo-para-muitas-amostras."><i class="fa fa-check"></i><b>1.7</b> Próximos passos: repetindo para muitas amostras.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="cap02.html"><a href="cap02.html"><i class="fa fa-check"></i><b>2</b> Métricas da paisagem</a>
<ul>
<li class="chapter" data-level="2.1" data-path="cap02.html"><a href="cap02.html#apresentação-1"><i class="fa fa-check"></i><b>2.1</b> Apresentação</a></li>
<li class="chapter" data-level="2.2" data-path="cap02.html"><a href="cap02.html#métricas-da-paisagem-e-pacote-landscapemetrics"><i class="fa fa-check"></i><b>2.2</b> Métricas da paisagem e pacote “landscapemetrics”</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="cap02.html"><a href="cap02.html#pacotes-1"><i class="fa fa-check"></i><b>2.2.1</b> Pacotes</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="cap02.html"><a href="cap02.html#dados-1"><i class="fa fa-check"></i><b>2.3</b> Dados</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="cap02.html"><a href="cap02.html#exibir-dados-raster-e-sobreposição-com-locais-de-amostragem"><i class="fa fa-check"></i><b>2.3.1</b> Exibir dados raster e sobreposição com locais de amostragem</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="cap02.html"><a href="cap02.html#calculo-de-métricas"><i class="fa fa-check"></i><b>2.4</b> Calculo de métricas</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="cap02.html"><a href="cap02.html#ponto-único-raio-único-métrica-única"><i class="fa fa-check"></i><b>2.4.1</b> Ponto único, raio único, métrica única</a></li>
<li class="chapter" data-level="2.4.2" data-path="cap02.html"><a href="cap02.html#ponto-único-distâncias-variados-métrica-única"><i class="fa fa-check"></i><b>2.4.2</b> Ponto único, distâncias variados, métrica única</a></li>
<li class="chapter" data-level="2.4.3" data-path="cap02.html"><a href="cap02.html#ponto-único-distâncias-variados-métricas-variadas"><i class="fa fa-check"></i><b>2.4.3</b> Ponto único, distâncias variados, métricas variadas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cap03.html"><a href="cap03.html"><i class="fa fa-check"></i><b>3</b> Respostas multiescala de espécies</a>
<ul>
<li class="chapter" data-level="3.1" data-path="cap03.html"><a href="cap03.html#apresentação-2"><i class="fa fa-check"></i><b>3.1</b> Apresentação</a></li>
<li class="chapter" data-level="3.2" data-path="cap03.html"><a href="cap03.html#pacotes-e-dados-1"><i class="fa fa-check"></i><b>3.2</b> Pacotes e dados</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="cap03.html"><a href="cap03.html#pacotes-2"><i class="fa fa-check"></i><b>3.2.1</b> Pacotes</a></li>
<li class="chapter" data-level="3.2.2" data-path="cap03.html"><a href="cap03.html#dados-necessarios"><i class="fa fa-check"></i><b>3.2.2</b> Dados necessarios</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="cap03.html"><a href="cap03.html#buffers"><i class="fa fa-check"></i><b>3.3</b> Buffers</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="cap03.html"><a href="cap03.html#floresta"><i class="fa fa-check"></i><b>3.3.1</b> Floresta</a></li>
<li class="chapter" data-level="3.3.2" data-path="cap03.html"><a href="cap03.html#especies"><i class="fa fa-check"></i><b>3.3.2</b> Especies</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="cap03.html"><a href="cap03.html#kernels"><i class="fa fa-check"></i><b>3.4</b> Kernels</a></li>
<li class="chapter" data-level="3.5" data-path="cap03.html"><a href="cap03.html#links-uteis"><i class="fa fa-check"></i><b>3.5</b> Links uteis</a></li>
</ul></li>
<li class="part"><span><b>III Exemplos de caso</b></span></li>
<li class="chapter" data-level="4" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html"><i class="fa fa-check"></i><b>4</b> Garimpo do Lourenço</a>
<ul>
<li class="chapter" data-level="4.1" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#apresentação-3"><i class="fa fa-check"></i><b>4.1</b> Apresentação</a></li>
<li class="chapter" data-level="4.2" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#pacotes-necessarios"><i class="fa fa-check"></i><b>4.2</b> Pacotes necessarios:</a></li>
<li class="chapter" data-level="4.3" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#área-de-estudo"><i class="fa fa-check"></i><b>4.3</b> Área de estudo</a></li>
<li class="chapter" data-level="4.4" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#dados-2"><i class="fa fa-check"></i><b>4.4</b> Dados</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#ponto-de-referência-epsg-4326"><i class="fa fa-check"></i><b>4.4.1</b> Ponto de referência (EPSG: 4326)</a></li>
<li class="chapter" data-level="4.4.2" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#ponto-de-referência-epsg-31976"><i class="fa fa-check"></i><b>4.4.2</b> Ponto de referência (EPSG: 31976)</a></li>
<li class="chapter" data-level="4.4.3" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#verificar-com-mapa-de-base-openstreetmap."><i class="fa fa-check"></i><b>4.4.3</b> Verificar com mapa de base (OpenStreetMap).</a></li>
<li class="chapter" data-level="4.4.4" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#dados-mapbiomas-cobertura-da-terra"><i class="fa fa-check"></i><b>4.4.4</b> Dados: MapBiomas cobertura da terra</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#calculo-de-métricas-1"><i class="fa fa-check"></i><b>4.5</b> Calculo de métricas</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#métricas-para-a-paisagem"><i class="fa fa-check"></i><b>4.5.1</b> Métricas para a paisagem</a></li>
<li class="chapter" data-level="4.5.2" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#métricas-para-as-classes"><i class="fa fa-check"></i><b>4.5.2</b> Métricas para as classes</a></li>
<li class="chapter" data-level="4.5.3" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#métricas-para-as-manchas"><i class="fa fa-check"></i><b>4.5.3</b> Métricas para as manchas</a></li>
<li class="chapter" data-level="4.5.4" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#quais-métricas-devo-escolher"><i class="fa fa-check"></i><b>4.5.4</b> Quais métricas devo escolher?</a></li>
<li class="chapter" data-level="4.5.5" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#métricas-por-classe-de-mineração"><i class="fa fa-check"></i><b>4.5.5</b> Métricas por classe de mineração</a></li>
<li class="chapter" data-level="4.5.6" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#exportar-as-métricas"><i class="fa fa-check"></i><b>4.5.6</b> Exportar as métricas</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#preparando-os-resultados"><i class="fa fa-check"></i><b>4.6</b> Preparando os resultados</a></li>
<li class="chapter" data-level="4.7" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#uma-tabela-versatil"><i class="fa fa-check"></i><b>4.7</b> Uma tabela versatil</a></li>
<li class="chapter" data-level="4.8" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#reorganização"><i class="fa fa-check"></i><b>4.8</b> Reorganização</a></li>
<li class="chapter" data-level="4.9" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#uma-figura-elegante"><i class="fa fa-check"></i><b>4.9</b> Uma figura elegante</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#gráfico-de-barra"><i class="fa fa-check"></i><b>4.9.1</b> Gráfico de barra</a></li>
<li class="chapter" data-level="4.9.2" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#gráfico-de-boxplot"><i class="fa fa-check"></i><b>4.9.2</b> Gráfico de boxplot</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#comparação-entre-anos"><i class="fa fa-check"></i><b>4.10</b> Comparação entre anos</a></li>
<li class="chapter" data-level="4.11" data-path="garimpo-do-lourenço.html"><a href="garimpo-do-lourenço.html#conclusões-e-próximos-passos"><i class="fa fa-check"></i><b>4.11</b> Conclusões e próximos passos</a></li>
</ul></li>
<li class="part"><span><b>IV R e RStudio: Codigo com certeza</b></span></li>
<li class="chapter" data-level="5" data-path="cap20.html"><a href="cap20.html"><i class="fa fa-check"></i><b>5</b> Pré-requisitos</a>
<ul>
<li class="chapter" data-level="5.1" data-path="cap20.html"><a href="cap20.html#introdução-1"><i class="fa fa-check"></i><b>5.1</b> Introdução</a></li>
<li class="chapter" data-level="5.2" data-path="cap20.html"><a href="cap20.html#instalação-do-r"><i class="fa fa-check"></i><b>5.2</b> Instalação do R</a></li>
<li class="chapter" data-level="5.3" data-path="cap20.html"><a href="cap20.html#instalação-do-rstudio"><i class="fa fa-check"></i><b>5.3</b> Instalação do RStudio</a></li>
<li class="chapter" data-level="5.4" data-path="cap20.html"><a href="cap20.html#versão-do-r"><i class="fa fa-check"></i><b>5.4</b> Versão do R</a></li>
<li class="chapter" data-level="5.5" data-path="cap20.html"><a href="cap20.html#pacotes-3"><i class="fa fa-check"></i><b>5.5</b> Pacotes</a></li>
<li class="chapter" data-level="5.6" data-path="cap20.html"><a href="cap20.html#dados-3"><i class="fa fa-check"></i><b>5.6</b> Dados</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="cap21.html"><a href="cap21.html"><i class="fa fa-check"></i><b>6</b> Introdução ao R</a>
<ul>
<li class="chapter" data-level="" data-path="cap21.html"><a href="cap21.html#pré-requisitos-do-capítulo"><i class="fa fa-check"></i>Pré-requisitos do capítulo</a></li>
<li class="chapter" data-level="6.1" data-path="cap21.html"><a href="cap21.html#contextualização"><i class="fa fa-check"></i><b>6.1</b> Contextualização</a></li>
<li class="chapter" data-level="6.2" data-path="cap21.html"><a href="cap21.html#r-e-rstudio"><i class="fa fa-check"></i><b>6.2</b> R e RStudio</a></li>
<li class="chapter" data-level="6.3" data-path="cap21.html"><a href="cap21.html#funcionamento-da-linguagem-r"><i class="fa fa-check"></i><b>6.3</b> Funcionamento da linguagem R</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="cap21.html"><a href="cap21.html#console"><i class="fa fa-check"></i><b>6.3.1</b> Console</a></li>
<li class="chapter" data-level="6.3.2" data-path="cap21.html"><a href="cap21.html#scripts"><i class="fa fa-check"></i><b>6.3.2</b> Scripts</a></li>
<li class="chapter" data-level="6.3.3" data-path="cap21.html"><a href="cap21.html#operadores"><i class="fa fa-check"></i><b>6.3.3</b> Operadores</a></li>
<li class="chapter" data-level="6.3.4" data-path="cap21.html"><a href="cap21.html#objetos"><i class="fa fa-check"></i><b>6.3.4</b> Objetos</a></li>
<li class="chapter" data-level="6.3.5" data-path="cap21.html"><a href="cap21.html#funções"><i class="fa fa-check"></i><b>6.3.5</b> Funções</a></li>
<li class="chapter" data-level="6.3.6" data-path="cap21.html"><a href="cap21.html#pacotes-4"><i class="fa fa-check"></i><b>6.3.6</b> Pacotes</a></li>
<li class="chapter" data-level="6.3.7" data-path="cap21.html"><a href="cap21.html#ajuda-help"><i class="fa fa-check"></i><b>6.3.7</b> Ajuda (<em>Help</em>)</a></li>
<li class="chapter" data-level="6.3.8" data-path="cap21.html"><a href="cap21.html#ambiente-environment"><i class="fa fa-check"></i><b>6.3.8</b> Ambiente (<em>Environment</em>)</a></li>
<li class="chapter" data-level="6.3.9" data-path="cap21.html"><a href="cap21.html#citações"><i class="fa fa-check"></i><b>6.3.9</b> Citações</a></li>
<li class="chapter" data-level="6.3.10" data-path="cap21.html"><a href="cap21.html#principais-erros-de-iniciantes"><i class="fa fa-check"></i><b>6.3.10</b> Principais erros de iniciantes</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="cap21.html"><a href="cap21.html#estrutura-e-manipulação-de-objetos"><i class="fa fa-check"></i><b>6.4</b> Estrutura e manipulação de objetos</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="cap21.html"><a href="cap21.html#atributo-dos-objetos"><i class="fa fa-check"></i><b>6.4.1</b> Atributo dos objetos</a></li>
<li class="chapter" data-level="6.4.2" data-path="cap21.html"><a href="cap21.html#manipulação-de-objetos-unidimensionais"><i class="fa fa-check"></i><b>6.4.2</b> Manipulação de objetos unidimensionais</a></li>
<li class="chapter" data-level="6.4.3" data-path="cap21.html"><a href="cap21.html#manipulação-de-objetos-multidimensionais"><i class="fa fa-check"></i><b>6.4.3</b> Manipulação de objetos multidimensionais</a></li>
<li class="chapter" data-level="6.4.4" data-path="cap21.html"><a href="cap21.html#valores-faltantes-e-especiais"><i class="fa fa-check"></i><b>6.4.4</b> Valores faltantes e especiais</a></li>
<li class="chapter" data-level="6.4.5" data-path="cap21.html"><a href="cap21.html#diretório-de-trabalho"><i class="fa fa-check"></i><b>6.4.5</b> Diretório de trabalho</a></li>
<li class="chapter" data-level="6.4.6" data-path="cap21.html"><a href="cap21.html#importar-dados"><i class="fa fa-check"></i><b>6.4.6</b> Importar dados</a></li>
<li class="chapter" data-level="6.4.7" data-path="cap21.html"><a href="cap21.html#conferência-dos-dados-importados"><i class="fa fa-check"></i><b>6.4.7</b> Conferência dos dados importados</a></li>
<li class="chapter" data-level="6.4.8" data-path="cap21.html"><a href="cap21.html#exportar-dados"><i class="fa fa-check"></i><b>6.4.8</b> Exportar dados</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="cap21.html"><a href="cap21.html#para-se-aprofundar"><i class="fa fa-check"></i><b>6.5</b> Para se aprofundar</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="cap21.html"><a href="cap21.html#livros"><i class="fa fa-check"></i><b>6.5.1</b> Livros</a></li>
<li class="chapter" data-level="6.5.2" data-path="cap21.html"><a href="cap21.html#links"><i class="fa fa-check"></i><b>6.5.2</b> Links</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="cap21.html"><a href="cap21.html#exercícios"><i class="fa fa-check"></i><b>6.6</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="cap22.html"><a href="cap22.html"><i class="fa fa-check"></i><b>7</b> Tidyverse</a>
<ul>
<li class="chapter" data-level="" data-path="cap22.html"><a href="cap22.html#pré-requisitos-do-capítulo-1"><i class="fa fa-check"></i>Pré-requisitos do capítulo</a></li>
<li class="chapter" data-level="7.1" data-path="cap22.html"><a href="cap22.html#contextualização-1"><i class="fa fa-check"></i><b>7.1</b> Contextualização</a></li>
<li class="chapter" data-level="7.2" data-path="cap22.html"><a href="cap22.html#tidyverse"><i class="fa fa-check"></i><b>7.2</b> <em>tidyverse</em></a></li>
<li class="chapter" data-level="7.3" data-path="cap22.html"><a href="cap22.html#readr-readxl-e-writexl"><i class="fa fa-check"></i><b>7.3</b> readr, readxl e writexl</a></li>
<li class="chapter" data-level="7.4" data-path="cap22.html"><a href="cap22.html#tibble"><i class="fa fa-check"></i><b>7.4</b> tibble</a></li>
<li class="chapter" data-level="7.5" data-path="cap22.html"><a href="cap22.html#pipe-base-e-magrittr"><i class="fa fa-check"></i><b>7.5</b> pipe: base (|&gt;) e magrittr (%&gt;%)</a></li>
<li class="chapter" data-level="7.6" data-path="cap22.html"><a href="cap22.html#tidyr"><i class="fa fa-check"></i><b>7.6</b> tidyr</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="cap22.html"><a href="cap22.html#palmerpenguins"><i class="fa fa-check"></i><b>7.6.1</b> palmerpenguins</a></li>
<li class="chapter" data-level="7.6.2" data-path="cap22.html"><a href="cap22.html#glimpse"><i class="fa fa-check"></i><b>7.6.2</b> glimpse()</a></li>
<li class="chapter" data-level="7.6.3" data-path="cap22.html"><a href="cap22.html#unite"><i class="fa fa-check"></i><b>7.6.3</b> unite()</a></li>
<li class="chapter" data-level="7.6.4" data-path="cap22.html"><a href="cap22.html#separate"><i class="fa fa-check"></i><b>7.6.4</b> separate()</a></li>
<li class="chapter" data-level="7.6.5" data-path="cap22.html"><a href="cap22.html#drop_na-e-replace_na"><i class="fa fa-check"></i><b>7.6.5</b> drop_na() e replace_na()</a></li>
<li class="chapter" data-level="7.6.6" data-path="cap22.html"><a href="cap22.html#pivot_longer-e-pivot_wider"><i class="fa fa-check"></i><b>7.6.6</b> pivot_longer() e pivot_wider()</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="cap22.html"><a href="cap22.html#dplyr"><i class="fa fa-check"></i><b>7.7</b> dplyr</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="cap22.html"><a href="cap22.html#gramática"><i class="fa fa-check"></i><b>7.7.1</b> Gramática</a></li>
<li class="chapter" data-level="7.7.2" data-path="cap22.html"><a href="cap22.html#sintaxe"><i class="fa fa-check"></i><b>7.7.2</b> Sintaxe</a></li>
<li class="chapter" data-level="7.7.3" data-path="cap22.html"><a href="cap22.html#palmerpenguins-1"><i class="fa fa-check"></i><b>7.7.3</b> palmerpenguins</a></li>
<li class="chapter" data-level="7.7.4" data-path="cap22.html"><a href="cap22.html#relocate"><i class="fa fa-check"></i><b>7.7.4</b> relocate()</a></li>
<li class="chapter" data-level="7.7.5" data-path="cap22.html"><a href="cap22.html#rename"><i class="fa fa-check"></i><b>7.7.5</b> rename()</a></li>
<li class="chapter" data-level="7.7.6" data-path="cap22.html"><a href="cap22.html#select"><i class="fa fa-check"></i><b>7.7.6</b> select()</a></li>
<li class="chapter" data-level="7.7.7" data-path="cap22.html"><a href="cap22.html#pull"><i class="fa fa-check"></i><b>7.7.7</b> pull()</a></li>
<li class="chapter" data-level="7.7.8" data-path="cap22.html"><a href="cap22.html#mutate"><i class="fa fa-check"></i><b>7.7.8</b> mutate()</a></li>
<li class="chapter" data-level="7.7.9" data-path="cap22.html"><a href="cap22.html#arrange"><i class="fa fa-check"></i><b>7.7.9</b> arrange()</a></li>
<li class="chapter" data-level="7.7.10" data-path="cap22.html"><a href="cap22.html#filter"><i class="fa fa-check"></i><b>7.7.10</b> filter()</a></li>
<li class="chapter" data-level="7.7.11" data-path="cap22.html"><a href="cap22.html#slice"><i class="fa fa-check"></i><b>7.7.11</b> slice()</a></li>
<li class="chapter" data-level="7.7.12" data-path="cap22.html"><a href="cap22.html#distinct"><i class="fa fa-check"></i><b>7.7.12</b> distinct()</a></li>
<li class="chapter" data-level="7.7.13" data-path="cap22.html"><a href="cap22.html#count"><i class="fa fa-check"></i><b>7.7.13</b> count()</a></li>
<li class="chapter" data-level="7.7.14" data-path="cap22.html"><a href="cap22.html#group_by"><i class="fa fa-check"></i><b>7.7.14</b> group_by()</a></li>
<li class="chapter" data-level="7.7.15" data-path="cap22.html"><a href="cap22.html#summarise"><i class="fa fa-check"></i><b>7.7.15</b> summarise()</a></li>
<li class="chapter" data-level="7.7.16" data-path="cap22.html"><a href="cap22.html#bind_rows-e-bind_cols"><i class="fa fa-check"></i><b>7.7.16</b> bind_rows() e bind_cols()</a></li>
<li class="chapter" data-level="7.7.17" data-path="cap22.html"><a href="cap22.html#join"><i class="fa fa-check"></i><b>7.7.17</b> *_join()</a></li>
<li class="chapter" data-level="7.7.18" data-path="cap22.html"><a href="cap22.html#operações-de-conjuntos-e-comparação-de-dados"><i class="fa fa-check"></i><b>7.7.18</b> Operações de conjuntos e comparação de dados</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="cap22.html"><a href="cap22.html#stringr"><i class="fa fa-check"></i><b>7.8</b> stringr</a></li>
<li class="chapter" data-level="7.9" data-path="cap22.html"><a href="cap22.html#forcats"><i class="fa fa-check"></i><b>7.9</b> forcats</a></li>
<li class="chapter" data-level="7.10" data-path="cap22.html"><a href="cap22.html#lubridate"><i class="fa fa-check"></i><b>7.10</b> lubridate</a></li>
<li class="chapter" data-level="7.11" data-path="cap22.html"><a href="cap22.html#purrr"><i class="fa fa-check"></i><b>7.11</b> purrr</a></li>
<li class="chapter" data-level="7.12" data-path="cap22.html"><a href="cap22.html#para-se-aprofundar-1"><i class="fa fa-check"></i><b>7.12</b> Para se aprofundar</a>
<ul>
<li class="chapter" data-level="7.12.1" data-path="cap22.html"><a href="cap22.html#livros-1"><i class="fa fa-check"></i><b>7.12.1</b> Livros</a></li>
<li class="chapter" data-level="7.12.2" data-path="cap22.html"><a href="cap22.html#links-1"><i class="fa fa-check"></i><b>7.12.2</b> Links</a></li>
</ul></li>
<li class="chapter" data-level="7.13" data-path="cap22.html"><a href="cap22.html#exercícios-1"><i class="fa fa-check"></i><b>7.13</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="cap23.html"><a href="cap23.html"><i class="fa fa-check"></i><b>8</b> Visualização de dados</a>
<ul>
<li class="chapter" data-level="" data-path="cap23.html"><a href="cap23.html#pré-requisitos-do-capítulo-2"><i class="fa fa-check"></i>Pré-requisitos do capítulo</a></li>
<li class="chapter" data-level="8.1" data-path="cap23.html"><a href="cap23.html#contextualização-2"><i class="fa fa-check"></i><b>8.1</b> Contextualização</a></li>
<li class="chapter" data-level="8.2" data-path="cap23.html"><a href="cap23.html#principais-pacotes"><i class="fa fa-check"></i><b>8.2</b> Principais pacotes</a></li>
<li class="chapter" data-level="8.3" data-path="cap23.html"><a href="cap23.html#grámatica-dos-gráficos"><i class="fa fa-check"></i><b>8.3</b> Grámatica dos gráficos</a></li>
<li class="chapter" data-level="8.4" data-path="cap23.html"><a href="cap23.html#tipos-de-gráficos"><i class="fa fa-check"></i><b>8.4</b> Tipos de gráficos</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="cap23.html"><a href="cap23.html#histograma-histogram"><i class="fa fa-check"></i><b>8.4.1</b> Histograma (<em>histogram</em>)</a></li>
<li class="chapter" data-level="8.4.2" data-path="cap23.html"><a href="cap23.html#gráfico-de-densidade-density-plot"><i class="fa fa-check"></i><b>8.4.2</b> Gráfico de densidade (<em>density plot</em>)</a></li>
<li class="chapter" data-level="8.4.3" data-path="cap23.html"><a href="cap23.html#diagrama-de-pontos-dot-plot"><i class="fa fa-check"></i><b>8.4.3</b> Diagrama de pontos (<em>dot plot</em>)</a></li>
<li class="chapter" data-level="8.4.4" data-path="cap23.html"><a href="cap23.html#gráfico-de-barras-bar-plot"><i class="fa fa-check"></i><b>8.4.4</b> Gráfico de barras (<em>bar plot</em>)</a></li>
<li class="chapter" data-level="8.4.5" data-path="cap23.html"><a href="cap23.html#gráfico-de-setores-pie-chart-e-donut-chart"><i class="fa fa-check"></i><b>8.4.5</b> Gráfico de setores (<em>pie chart</em> e <em>donut chart</em>)</a></li>
<li class="chapter" data-level="8.4.6" data-path="cap23.html"><a href="cap23.html#gráfico-de-caixa-boxplot"><i class="fa fa-check"></i><b>8.4.6</b> Gráfico de caixa (<em>boxplot</em>)</a></li>
<li class="chapter" data-level="8.4.7" data-path="cap23.html"><a href="cap23.html#gráfico-de-dispersão-scatter-plot"><i class="fa fa-check"></i><b>8.4.7</b> Gráfico de dispersão (<em>scatter plot</em>)</a></li>
<li class="chapter" data-level="8.4.8" data-path="cap23.html"><a href="cap23.html#visualização-de-múltiplos-gráficos-pareados"><i class="fa fa-check"></i><b>8.4.8</b> Visualização de múltiplos gráficos pareados</a></li>
<li class="chapter" data-level="8.4.9" data-path="cap23.html"><a href="cap23.html#erros-comuns-dos-usuários-do-ggplot2-e-como-evitá-los"><i class="fa fa-check"></i><b>8.4.9</b> Erros comuns dos usuários do <code>ggplot2</code> e como evitá-los</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="cap23.html"><a href="cap23.html#finalização-de-gráficos-para-publicação"><i class="fa fa-check"></i><b>8.5</b> Finalização de gráficos para publicação</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="cap23.html"><a href="cap23.html#posição-cores-e-fonte-da-legenda"><i class="fa fa-check"></i><b>8.5.1</b> Posição, cores e fonte da legenda</a></li>
<li class="chapter" data-level="8.5.2" data-path="cap23.html"><a href="cap23.html#elementos-gráficos-eixo-fonte-gride"><i class="fa fa-check"></i><b>8.5.2</b> Elementos gráficos: eixo, fonte, gride</a></li>
<li class="chapter" data-level="8.5.3" data-path="cap23.html"><a href="cap23.html#temas-personalizados-ggtheme"><i class="fa fa-check"></i><b>8.5.3</b> Temas personalizados <code>ggtheme()</code></a></li>
<li class="chapter" data-level="8.5.4" data-path="cap23.html"><a href="cap23.html#exportando-gráficos-com-alta-qualidade-com-a-função-ggsave"><i class="fa fa-check"></i><b>8.5.4</b> Exportando gráficos com alta qualidade com a função <code>ggsave()</code></a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="cap23.html"><a href="cap23.html#para-se-aprofundar-2"><i class="fa fa-check"></i><b>8.6</b> Para se aprofundar</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="cap23.html"><a href="cap23.html#livros-2"><i class="fa fa-check"></i><b>8.6.1</b> Livros</a></li>
<li class="chapter" data-level="8.6.2" data-path="cap23.html"><a href="cap23.html#links-2"><i class="fa fa-check"></i><b>8.6.2</b> Links</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="cap23.html"><a href="cap23.html#exercícios-2"><i class="fa fa-check"></i><b>8.7</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="cap25.html"><a href="cap25.html"><i class="fa fa-check"></i><b>9</b> Primeiros passos com uma raster</a>
<ul>
<li class="chapter" data-level="9.0.1" data-path="cap25.html"><a href="cap25.html#obter-e-carregar-dados-raster-1"><i class="fa fa-check"></i><b>9.0.1</b> Obter e carregar dados (raster)</a></li>
<li class="chapter" data-level="9.0.2" data-path="cap25.html"><a href="cap25.html#reclassificação-1"><i class="fa fa-check"></i><b>9.0.2</b> Reclassificação</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="primeiros-passos-com-vector.html"><a href="primeiros-passos-com-vector.html"><i class="fa fa-check"></i><b>10</b> Primeiros passos com vector</a>
<ul>
<li class="chapter" data-level="10.1" data-path="primeiros-passos-com-vector.html"><a href="primeiros-passos-com-vector.html#obter-e-carregar-dados-vectores-1"><i class="fa fa-check"></i><b>10.1</b> Obter e carregar dados (vectores)</a></li>
<li class="chapter" data-level="10.2" data-path="primeiros-passos-com-vector.html"><a href="primeiros-passos-com-vector.html#visualizar-os-arquivos-camadas-vector-1"><i class="fa fa-check"></i><b>10.2</b> Visualizar os arquivos (camadas vector)</a></li>
</ul></li>
<li class="part"><span><b>V Encerramento</b></span></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografia</a></li>
<li class="chapter" data-level="" data-path="glossário.html"><a href="glossário.html"><i class="fa fa-check"></i>Glossário</a></li>
<li class="chapter" data-level="" data-path=""><a href="#appendix-apêndice"><i class="fa fa-check"></i>(APPENDIX) Apêndice</a>
<ul>
<li class="chapter" data-level="10.3" data-path="glossário.html"><a href="glossário.html#download-mapbiomas-cover"><i class="fa fa-check"></i><b>10.3</b> Download mapbiomas cover</a></li>
<li class="chapter" data-level="10.4" data-path="glossário.html"><a href="glossário.html#crop-mapbiomas-cover"><i class="fa fa-check"></i><b>10.4</b> Crop mapbiomas cover</a></li>
<li class="chapter" data-level="10.5" data-path="glossário.html"><a href="glossário.html#plot-with-legend"><i class="fa fa-check"></i><b>10.5</b> Plot with legend</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="soluções-de-exercícios.html"><a href="soluções-de-exercícios.html"><i class="fa fa-check"></i><b>11</b> Soluções de exercícios</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Ecologia de Paisagens com R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="cap03" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> Respostas multiescala de espécies<a href="cap03.html#cap03" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="apresentação-2" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Apresentação<a href="cap03.html#apresentação-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Este capitulo pretende ilustrar a abordagem geral de identificação de escalas de efeitos nas relações ambientais usando R. Usaremos conteudo baseado no Capítulo 2 do livro <a href="https://doi.org/10.1007/978-3-030-01989-1">Spatial Ecology and Conservation Modeling</a> <span class="citation">(Fletcher and Fortin 2018)</span> . Aqui interpretamos a escala em que as espécies podem responder ao habitat, como a cobertura florestal. Para fazer isso, quantificamos a quantidade de floresta que ocorre a várias distâncias dos pontos de amostragem e, em seguida, determinamos a escala em que a cobertura florestal melhor prevê a ocorrência de espécies.</p>
<p>Consideramos como podemos relacionar diferenças de escala (extensão) com a ocorrência de espécies para ajudar a identificar a escala característica (ou escala de efeito) da cobertura florestal na ocorrência de espécies. Este é um problema cada vez mais considerado na ecologia aplicada (Holland et al. 2004; Jackson e Fahrig 2015; McGarigal et al. 2016; Miguet et al. 2016).</p>
<p>Existem várias maneiras de quantificar a escala de efeito. Uma abordagem é usar zonas tampão (daqui adiante “buffers”) de diferentes tamanhos para medir a paisagem circundante aos locais de amostragem. Essa abordagem foi popularizada por Pearson (1993) e é amplamente utilizada por outros pesquisadores (Holland et al. 2004; Jackson e Fahrig 2015).</p>
<p>Um método alternativo emprega uma função de suavização ponderada pela distância - Kernels espaciais. Os kernels podem ser usados para ponderar os dados com base na distância do local de amostreagem. Isso ajuda a capturar melhor os efeitos da vizinhança, ponderando mais os locais próximos do que os distantes. Chandler e Hepinstall-Cymerman <span class="citation">(2016)</span> mostraram como os kernels espaciais podem ser usados para selecionar a escala de efeito sem recorrer a binning a priori (como por exemplo, os buffers de 1 km no capítulo “Métricas”).</p>
<p>Neste capitulo, primeiramente ilustramos o uso de buffers de diferentes distancias e depois ilustramos o uso de kernels espaciais.</p>
</div>
<div id="pacotes-e-dados-1" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Pacotes e dados<a href="cap03.html#pacotes-e-dados-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="pacotes-2" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Pacotes<a href="cap03.html#pacotes-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Carregar pacotes (que deve esta instalado antes):</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="cap03.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(eprdados)</span>
<span id="cb1-2"><a href="cap03.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="cap03.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-4"><a href="cap03.html#cb1-4" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-5"><a href="cap03.html#cb1-5" tabindex="-1"></a><span class="fu">library</span>(siland)</span></code></pre></div>
<p>Caso os pacotes não tenham sido instalados, o R vai avisar atraves um mensagem tipo: <span style="     color: red !important;">Error in library(nomepacote) there is no package called nomepacote</span>. Neste caso, para instalá-los consulte o capitulos aqui <a href="https://livro.curso-r.com/4-1-instala%C3%A7%C3%A3o-de-pacotes.html">Capitulo 4 instalação de pacotes</a> e aqui <a href="https://analises-ecologicas.com/cap4#pacotes-1">Capitulo 4 pacotes</a> .</p>
</div>
<div id="dados-necessarios" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Dados necessarios<a href="cap03.html#dados-necessarios" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A fazer.</p>
</div>
</div>
<div id="buffers" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Buffers<a href="cap03.html#buffers" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Agora investigamos a escala em que as espécies podem responder ao habitat, como a cobertura florestal. Para fazer isso, quantificamos a quantidade de floresta que ocorre em várias distâncias e, em seguida, determinamos a escala em que a cobertura florestal melhor explica a ocorrência das espécies.</p>
<div id="floresta" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Floresta<a href="cap03.html#floresta" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Primeiramente, olhamos a proporção de cobertura florestal em diferentes escalas (distâncias de buffer) para todos os pontos. Esses dados ja foram calculados seguindo os passos no capitulo “Métricas”. Para nos auxilia à ter uma visão geral do conjunto de dados e de suas interrelações podemos apresentar como um gráfico pareado. Esse gráfico também é chamado de “pairs plot” ou “correlograma”. A função <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: #dedede !important;">ggpairs()</span> do pacote <a href="https://ggobi.github.io/ggally/index.html">GGally</a> permite criar múltiplos gráficos pareados comparando as variáveis contínuas no seu conjunto de dados. Além de demonstrar gráficos de dispersão de cada par de variáveis, ela apresenta gráficos de densidade de cada variável individualmente e, além disso, os valores de correlação entre os pares analisados. Mais detalhes sobre a função <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: #dedede !important;">ggpairs()</span> no Capítulo <a href="cap23.html#cap23">8</a>.</p>
<p>Ao fazê-lo, descobrimos que a percentagem de cobertura florestal em diferentes escalas tende a ser altamente correlacionada. Isto não é surpreendente, dado que os cálculos com um tamanho de buffer maior incluem a área em tamanhos de buffer menores.</p>
<pre><code>##   aid Latitude Longitude Habitat_WWF class class_description metric
## 1   1 -0.01624 -51.10926     Cerrado     1            Forest cpland
## 2   1 -0.01624 -51.10926     Cerrado     1            Forest cpland
## 3   1 -0.01624 -51.10926     Cerrado     1            Forest cpland
## 4   1 -0.01624 -51.10926     Cerrado     1            Forest cpland
## 5   1 -0.01624 -51.10926     Cerrado     1            Forest cpland
## 6   1 -0.01624 -51.10926     Cerrado     1            Forest cpland
##   buff_dist_km  buff_metric value_median
## 1        0.125 cpland_0.125     3.225806
## 2        0.250  cpland_0.25    34.583333
## 3        0.500   cpland_0.5    51.113468
## 4        1.000     cpland_1    47.513053
## 5       16.000    cpland_16    22.700354
## 6        2.000     cpland_2    30.515579</code></pre>
plot correlations
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plot-pairs"></span>
<img src="figures/fig_pairs.png" alt="Cobertura florestal em torno dos locais de amostragem, calculada em diferentes escalas. São mostrados gráficos de dispersão da porcentagem de cobertura florestal para cada combinação de escalas em pares. Observe o alto grau de correlação entre as escalas similares (125 e 250 metros por exemplo) e escalas maiores (acima de 1 km)." width="75%" height="75%" />
<p class="caption">
Figura 3.1: Cobertura florestal em torno dos locais de amostragem, calculada em diferentes escalas. São mostrados gráficos de dispersão da porcentagem de cobertura florestal para cada combinação de escalas em pares. Observe o alto grau de correlação entre as escalas similares (125 e 250 metros por exemplo) e escalas maiores (acima de 1 km).
</p>
</div>
</div>
<div id="especies" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Especies<a href="cap03.html#especies" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para entender como a cobertura florestal afeta a ocorrência de espécies, usamos um modelo de regressão logística. Esse modelo é usado para prever a probabilidade de um evento ocorrer, como a presença de uma espécie. No caso da regressão logística, o evento é a presença de uma espécie (1) ou sua ausência (0). A regressão logística funciona de forma semelhante à regressão linear, mas é adaptada para dados binários. Na regressão linear, o modelo prevê um valor contínuo, como o tamanho do corpo de um animal. Na regressão logística, o modelo prevê a probabilidade de um evento ocorrer, como a presença de uma espécie. O modelo de regressão logística que usamos é simples, e não leva em conta todos os fatores que podem afetar a ocorrência de espécies. No entanto, é útil para ilustrar como efeitos de escala na cobertura florestal pode afetar nossa entendimento sobre a ocorrência de espécies.</p>
<p>Comparamos diferentes modelos com base em medições de cobertura florestal em diferentes escalas - extensões locais (tamanhos de buffer). Para comparar os modelos com tamanhos de buffer diferentes, podemos usar medidas, como medidas de ajuste (verossimilhança), a variação explicada e/ou o sucesso preditivo.</p>
<p>Para comparar o ajuste de modelos diferentes, usamos a log-verossimilhança, que tem um forte base filosófica em estatística. log-verossimilhanças são baseadas no conceito de máxima verossimilhança e quantificam a plausibilidade de um modelo, dados os dados. Ela é baseada no conceito de máxima verossimilhança, que é uma técnica estatística para estimar os parâmetros de um modelo a partir dos dados.</p>
<p>Neste estudo, comparamos modelos que possuem o mesmo número de parâmetros. Isso é importante porque permite que os resultados sejam interpretados com mais confiança. Se os modelos tivessem diferentes números de parâmetros, seria difícil dizer se as diferenças nos resultados eram devido às diferenças nas escalas espaciais ou ao número de parâmetros. Assim sendo, neste caso, o uso de alternativos como critérios de seleção de modelos, como o Critério de Informação de Akaike, que penaliza a log-verossimilhança com base no número de parâmetros (Burnham e Anderson 1998), forneceria resultados idênticos.</p>
<p>Primeiramente vamos rodar as analises para uma especie.
Isso seria um exemplo mostrando os passos.</p>
<div id="terminologia" class="section level4 hasAnchor" number="3.3.2.1">
<h4><span class="header-section-number">3.3.2.1</span> terminologia<a href="cap03.html#terminologia" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Vamos nos referir a:</p>
<ul>
<li><span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: #dedede !important;">sp_pa</span> como variável dependente/resposta, com o valor observado (1 ou 0) denominado respostas.</li>
</ul>
<p>As outras variáveis são referidas como variáveis independentes, mas classificaremos adicionalmente:</p>
<ul>
<li><p>A <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: #dedede !important;">buff_dist_km</span> como variável de desenho (isto foi controlada pelo experimentador).</p></li>
<li><p>A <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: #dedede !important;">value_median</span> como variável independente/explanatoria; um covariável específica do ponto de amostragem (proprieadade rural) e distância de buffer.</p></li>
</ul>
<p>A forma estrutural do modelo de regressão logística é:</p>
<div align="center">
<span class="math inline">\(logit( E[Y_i | X_i]) = logit(p_i) = ln(\frac{p_i}{1 - p_i}) = \beta_0 + \beta_1 X_{1i} + \epsilon\)</span>
</div>
<p><br />
</p>
<p>Typical notation of the linear regression include:</p>
<ul>
<li><span class="math inline">\(Y_i\)</span> denotes the outcome (or dependent) variable for subject <span class="math inline">\(i\)</span>; this is a binary variable</li>
<li><span class="math inline">\(X_{1i}\)</span> denotes the predictor of interest or the independent variable (<span class="math inline">\(X_1\)</span>) for subject <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\beta_0\)</span> denotes the Y-intercept when <span class="math inline">\(X\)</span> is zero; this is not informative for logistic regression models</li>
<li><span class="math inline">\(\beta_1\)</span> denotes the slope or the change in <span class="math inline">\(Y\)</span> with a 1-unit change in <span class="math inline">\(X\)</span></li>
<li><span class="math inline">\(p_{i}\)</span> denotes the probability of the event occurring</li>
<li><span class="math inline">\(\epsilon\)</span> denotes the errors</li>
</ul>
<p>Neste exemplo, analisamos a ocorrência da espécie “sppD” em relação à cobertura florestal. Para variáveis independentes contínuas como proporção de floresta ( <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: #dedede !important;">value_median</span> ), podemos tentar gráficos de caixa (boxplots) de cada variável independente com a variável dependente (presença-ausencia) tratada como um fator de agrupamento. Usamos boxplots para uma análise exploratória preliminar. Os boxplots mostram que, onde a espécie está presente, a cobertura florestal é, em média, mais elevada do que onde a espécie está ausente. No entanto, há uma variação substancial na cobertura florestal nos locais onde a espécie está ausente. Essa variação sugere que, embora a cobertura florestal seja um fator importante que influencia a ocorrência da espécie, outros fatores também podem desempenhar um papel. Por exemplo, a espécie pode estar sujeita a outros fatores de pressão, como a caça ou a competição com outras espécies.</p>
<div class="figure"><span style="display:block;" id="fig:fig-sppD"></span>
<img src="figures/fig_sppD_box.png" alt="Gráfico para explorar as relações entre as variáveis. Boxplot comparando área core de floresta entre a presença-ausença de uma espécie em escalas diferentes (distâncias de 0.125 a 4 km)." width="90%" height="90%" />
<p class="caption">
Figura 3.2: Gráfico para explorar as relações entre as variáveis. Boxplot comparando área core de floresta entre a presença-ausença de uma espécie em escalas diferentes (distâncias de 0.125 a 4 km).
</p>
</div>
</div>
<div id="pergunta-1-2" class="section level4 hasAnchor" number="3.3.2.2">
<h4><span class="header-section-number">3.3.2.2</span> Pergunta 1<a href="cap03.html#pergunta-1-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><span style=" font-weight: bold;    color: blue !important;">Identifique a espécie "sppD". Com base nos resultados dos boxplots e lendo os artigos (Michalski &amp; Peres 2005; Michalski &amp; Peres 2007), sugerem três espécies de carnívoros que poderiam apresentar os mesmos padrões do sppD? Que informações/resultados adicionais o ajudariam a identificar a espécie sppD com maior certeza? Justifique suas escolhas de forma clara e concisa.</span></p>
<hr />
<p>Os boxplots são muito úteis para análises exploratórias, mas não fornecem muitas informações para a compreensão da escala do efeito. O modelo de regressão logística é um modelo preditivo para dados binários. Conseqüentemente, o modelo de regressão logística pode gerar probabilidades de que uma amostra terá o resultado discreto dada(s) uma(s) variável(ões) de entrada. O modelo de regressão logística usa estimativa de máxima verossimilhança (Maximum Likelihood Estimation - MLE), que é uma probabilidade condicional que classifica o resultado se um determinado limite for atingido (por exemplo, &gt; 0,50). Portanto, o intervalo de probabilidade de um modelo de regressão logística está entre 0 e 1. A figura abaixo fornece um exemplo de função logística. Ele usa uma função logit para modelar um resultado binário. A função logit é o logaritmo natural das probabilidades. Por exemplo, se a probabilidade for &gt; 0,5, a função logit é positiva, se a probabilidade for &lt;0,5, a função logit é negativa.</p>
<p>Agora plotamos os dados, ajustando uma regressão logística para obter uma representação visual. É útil executar isso antes de executar os modelos, para que tenhamos uma ideia dos padrões que existem nos dados.</p>
<div class="figure"><span style="display:block;" id="fig:fig-sppd-lr"></span>
<img src="figures/fig_sppD_lr.png" alt="Gráfico para explorar as relações entre as variáveis. Comparando a resposta de presença-ausença de uma espécie em escalas diferentes (distâncias de 0.125 a 4 km). Pontos mostram presença-ausência da espécie em 106 propriedades rurais. A linha azul é o ajuste de uma regressão logística." width="90%" height="90%" />
<p class="caption">
Figura 3.3: Gráfico para explorar as relações entre as variáveis. Comparando a resposta de presença-ausença de uma espécie em escalas diferentes (distâncias de 0.125 a 4 km). Pontos mostram presença-ausência da espécie em 106 propriedades rurais. A linha azul é o ajuste de uma regressão logística.
</p>
</div>
<p>Os graficos mostrarm a mesma padrao que os boxplots.
Uma impressão visual é útil. Mas devemos utilizar modelos estatísticos para fornecer evidências mais robustas e objetivas.
Usamos código que executará modelos simultaneamente para todas as distâncias de buffer. Podemos rodar a mesma com modelos e reultados separadamente para cada distância de buffer. Mas, seria pelo menos 50 linhas de codigo para rodar modelos e obter os resultados que precisamos. Aqui usamos funções oriundos do tinyverse e tidymodels para rodar os modelos e obter os resumos que precisamos em menos de 10 linhas.</p>
<p>Em menos de 10 linhas, incluimos funçoes para obter um conjunto de 8 modelos diferentes (um modelo para cada distância de buffer) e resultados associados.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="cap03.html#cb3-1" tabindex="-1"></a><span class="co"># Run models for sppD and 8 buffer distances</span></span>
<span id="cb3-2"><a href="cap03.html#cb3-2" tabindex="-1"></a>modelos_sppD <span class="ot">&lt;-</span> carnivoros <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="cap03.html#cb3-3" tabindex="-1"></a><span class="co"># filtro a especie desejada</span></span>
<span id="cb3-4"><a href="cap03.html#cb3-4" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(sp_name <span class="sc">==</span> <span class="st">&quot;sppD&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href="cap03.html#cb3-5" tabindex="-1"></a><span class="co"># selecionar as colunas que faz parte dos modelos</span></span>
<span id="cb3-6"><a href="cap03.html#cb3-6" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(sp_name, sp_pa, value_median, buff_dist_km) <span class="sc">|&gt;</span> </span>
<span id="cb3-7"><a href="cap03.html#cb3-7" tabindex="-1"></a><span class="co"># agrupar para rodar modelos diferentes para especie </span></span>
<span id="cb3-8"><a href="cap03.html#cb3-8" tabindex="-1"></a><span class="co"># e escala (distância de buffer)</span></span>
<span id="cb3-9"><a href="cap03.html#cb3-9" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">nest</span>(<span class="at">.by =</span> <span class="fu">c</span>(sp_name, buff_dist_km)) <span class="sc">|&gt;</span></span>
<span id="cb3-10"><a href="cap03.html#cb3-10" tabindex="-1"></a><span class="co"># especificar modelo e resumos desejados</span></span>
<span id="cb3-11"><a href="cap03.html#cb3-11" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb3-12"><a href="cap03.html#cb3-12" tabindex="-1"></a>    <span class="at">fit =</span> <span class="fu">map</span>(data, <span class="sc">~</span> <span class="fu">glm</span>(sp_pa <span class="sc">~</span> value_median,</span>
<span id="cb3-13"><a href="cap03.html#cb3-13" tabindex="-1"></a>      <span class="at">data =</span> .x, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>) </span>
<span id="cb3-14"><a href="cap03.html#cb3-14" tabindex="-1"></a>      ),</span>
<span id="cb3-15"><a href="cap03.html#cb3-15" tabindex="-1"></a>    <span class="at">tidied =</span> <span class="fu">map</span>(fit, broom<span class="sc">::</span>tidy, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>),</span>
<span id="cb3-16"><a href="cap03.html#cb3-16" tabindex="-1"></a>    <span class="at">glanced =</span> <span class="fu">map</span>(fit, broom<span class="sc">::</span>glance)</span>
<span id="cb3-17"><a href="cap03.html#cb3-17" tabindex="-1"></a>  )</span></code></pre></div>
<p>Olhar os resultados.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="cap03.html#cb4-1" tabindex="-1"></a>modelos_sppD <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="cap03.html#cb4-2" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(glanced)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 13
##   sp_name buff_dist_km data     fit    tidied   null.deviance df.null logLik
##   &lt;chr&gt;          &lt;dbl&gt; &lt;list&gt;   &lt;list&gt; &lt;list&gt;           &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt;
## 1 sppD           0.125 &lt;tibble&gt; &lt;glm&gt;  &lt;tibble&gt;          143.     105  -63.8
## 2 sppD           0.25  &lt;tibble&gt; &lt;glm&gt;  &lt;tibble&gt;          143.     105  -54.6
## 3 sppD           0.5   &lt;tibble&gt; &lt;glm&gt;  &lt;tibble&gt;          143.     105  -47.5
## 4 sppD           1     &lt;tibble&gt; &lt;glm&gt;  &lt;tibble&gt;          143.     105  -44.6
## 5 sppD          16     &lt;tibble&gt; &lt;glm&gt;  &lt;tibble&gt;          143.     105  -50.2
## 6 sppD           2     &lt;tibble&gt; &lt;glm&gt;  &lt;tibble&gt;          143.     105  -46.8
## 7 sppD           4     &lt;tibble&gt; &lt;glm&gt;  &lt;tibble&gt;          143.     105  -49.1
## 8 sppD           8     &lt;tibble&gt; &lt;glm&gt;  &lt;tibble&gt;          143.     105  -48.8
## # ℹ 5 more variables: AIC &lt;dbl&gt;, BIC &lt;dbl&gt;, deviance &lt;dbl&gt;, df.residual &lt;int&gt;,
## #   nobs &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="cap03.html#cb6-1" tabindex="-1"></a>modelos_sppD <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="cap03.html#cb6-2" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(tidied)</span></code></pre></div>
<pre><code>## # A tibble: 16 × 12
##    sp_name buff_dist_km data     fit    term        estimate std.error statistic
##    &lt;chr&gt;          &lt;dbl&gt; &lt;list&gt;   &lt;list&gt; &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 sppD           0.125 &lt;tibble&gt; &lt;glm&gt;  (Intercept)  -1.08      0.285      -3.81
##  2 sppD           0.125 &lt;tibble&gt; &lt;glm&gt;  value_medi…   0.0419    0.0114      3.68
##  3 sppD           0.25  &lt;tibble&gt; &lt;glm&gt;  (Intercept)  -2.46      0.514      -4.79
##  4 sppD           0.25  &lt;tibble&gt; &lt;glm&gt;  value_medi…   0.0662    0.0139      4.76
##  5 sppD           0.5   &lt;tibble&gt; &lt;glm&gt;  (Intercept)  -4.66      1.03       -4.51
##  6 sppD           0.5   &lt;tibble&gt; &lt;glm&gt;  value_medi…   0.0832    0.0177      4.70
##  7 sppD           1     &lt;tibble&gt; &lt;glm&gt;  (Intercept)  -5.89      1.35       -4.36
##  8 sppD           1     &lt;tibble&gt; &lt;glm&gt;  value_medi…   0.0853    0.0185      4.62
##  9 sppD          16     &lt;tibble&gt; &lt;glm&gt;  (Intercept)  -4.29      0.873      -4.91
## 10 sppD          16     &lt;tibble&gt; &lt;glm&gt;  value_medi…   0.0543    0.0106      5.13
## 11 sppD           2     &lt;tibble&gt; &lt;glm&gt;  (Intercept)  -5.45      1.22       -4.48
## 12 sppD           2     &lt;tibble&gt; &lt;glm&gt;  value_medi…   0.0726    0.0154      4.72
## 13 sppD           4     &lt;tibble&gt; &lt;glm&gt;  (Intercept)  -4.88      1.07       -4.58
## 14 sppD           4     &lt;tibble&gt; &lt;glm&gt;  value_medi…   0.0624    0.0130      4.80
## 15 sppD           8     &lt;tibble&gt; &lt;glm&gt;  (Intercept)  -4.55      0.958      -4.74
## 16 sppD           8     &lt;tibble&gt; &lt;glm&gt;  value_medi…   0.0575    0.0115      4.99
## # ℹ 4 more variables: p.value &lt;dbl&gt;, conf.low &lt;dbl&gt;, conf.high &lt;dbl&gt;,
## #   glanced &lt;list&gt;</code></pre>
<p>Compara scale of effect.
Pergunta: qual escala melhor se ajusta aos dados de presença-ausencia de sppD?</p>
Para identificar a escala do efeito da cobertura florestal na ocorrência de sppD, plotamos as log-verossimilhanças e AIC de diferentes modelos de regressão logística ajustados aos dados em função da cobertura florestal calculada em diferentes escalas, variando de 0.125 m a 16 km. Esperaríamos que a escala que melhor se ajustasse aos dados fosse a que melhor explicasse a variação na ocorrência. Nesse caso, descobrimos que a cobertura florestal dentro de 1 km é a que melhor se ajusta aos dados.
<div class="figure"><span style="display:block;" id="fig:fig-sppd-scale"></span>
<img src="figures/figg_sppD_logLikAIC.png" alt="a fazer" width="90%" height="90%" />
<p class="caption">
Figura 3.4: a fazer
</p>
</div>
<p>Pergunta: A relação entre a ocorrência de espécie sppD e a cobertura florestal é a mesma em diferentes escalas?
However, when plotting the β terms at different scales (Fig. 2.11b), we find that relationships are identical when forest cover is measured at 2 km or greater buffer sizes. In this situation, only at 500 m do we see a weak relationship with forest cover.</p>
<div class="figure"><span style="display:block;" id="fig:fig-sppd-scale-est"></span>
<img src="figures/figg_sppD_scale_est.png" alt="mais a fazer" width="90%" height="90%" />
<p class="caption">
Figura 3.5: mais a fazer
</p>
</div>
<p>Primeiro plotamos os dados.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="cap03.html#cb8-1" tabindex="-1"></a>carnivoros <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="cap03.html#cb8-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(buff_dist_km <span class="sc">&lt;</span> <span class="dv">4</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="cap03.html#cb8-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>value_median, <span class="at">y =</span> sp_pa)) <span class="sc">+</span> </span>
<span id="cb8-4"><a href="cap03.html#cb8-4" tabindex="-1"></a>      <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="dv">5</span>, <span class="at">height=</span><span class="fl">0.05</span>, <span class="at">alpha=</span><span class="fl">0.4</span>) <span class="sc">+</span> </span>
<span id="cb8-5"><a href="cap03.html#cb8-5" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.5</span>, <span class="at">linetype=</span><span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="cap03.html#cb8-6" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;glm&quot;</span>, </span>
<span id="cb8-7"><a href="cap03.html#cb8-7" tabindex="-1"></a>              <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>), </span>
<span id="cb8-8"><a href="cap03.html#cb8-8" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb8-9"><a href="cap03.html#cb8-9" tabindex="-1"></a>  <span class="fu">facet_grid</span>(sp_name<span class="sc">~</span>buff_dist_km) <span class="sc">+</span> </span>
<span id="cb8-10"><a href="cap03.html#cb8-10" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="st">&quot;presença (probabilidade)&quot;</span>, </span>
<span id="cb8-11"><a href="cap03.html#cb8-11" tabindex="-1"></a>                     <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.2</span>,<span class="fl">0.4</span>,<span class="fl">0.6</span>,<span class="fl">0.8</span>,<span class="fl">1.0</span>)) <span class="sc">+</span></span>
<span id="cb8-12"><a href="cap03.html#cb8-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;área core de floresta (%)&quot;</span>) <span class="ot">-&gt;</span> fig_spp_near</span>
<span id="cb8-13"><a href="cap03.html#cb8-13" tabindex="-1"></a>fig_spp_near</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="epr_files/figure-html/fig-species-logistic-1.png" width="672" /></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="cap03.html#cb10-1" tabindex="-1"></a>carnivoros <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="cap03.html#cb10-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>value_median, <span class="at">y =</span> sp_pa)) <span class="sc">+</span> </span>
<span id="cb10-3"><a href="cap03.html#cb10-3" tabindex="-1"></a>      <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="dv">5</span>, <span class="at">height=</span><span class="fl">0.05</span>, <span class="at">alpha=</span><span class="fl">0.4</span>) <span class="sc">+</span> </span>
<span id="cb10-4"><a href="cap03.html#cb10-4" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.5</span>, <span class="at">linetype=</span><span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="cap03.html#cb10-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;glm&quot;</span>, </span>
<span id="cb10-6"><a href="cap03.html#cb10-6" tabindex="-1"></a>              <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>), </span>
<span id="cb10-7"><a href="cap03.html#cb10-7" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb10-8"><a href="cap03.html#cb10-8" tabindex="-1"></a>  <span class="fu">facet_grid</span>(sp_name<span class="sc">~</span>buff_dist_km) <span class="sc">+</span> </span>
<span id="cb10-9"><a href="cap03.html#cb10-9" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="st">&quot;presença (probabilidade)&quot;</span>, </span>
<span id="cb10-10"><a href="cap03.html#cb10-10" tabindex="-1"></a>                     <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.2</span>,<span class="fl">0.4</span>,<span class="fl">0.6</span>,<span class="fl">0.8</span>,<span class="fl">1.0</span>)) <span class="sc">+</span></span>
<span id="cb10-11"><a href="cap03.html#cb10-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;área core de floresta (%)&quot;</span>) <span class="ot">-&gt;</span> fig_spp</span>
<span id="cb10-12"><a href="cap03.html#cb10-12" tabindex="-1"></a></span>
<span id="cb10-13"><a href="cap03.html#cb10-13" tabindex="-1"></a>fig_spp</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="epr_files/figure-html/fig-species-logistic-2.png" width="672" /></p>
<p>Modelos.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="cap03.html#cb12-1" tabindex="-1"></a><span class="co">#Run models for three species and 8 buffer distances</span></span>
<span id="cb12-2"><a href="cap03.html#cb12-2" tabindex="-1"></a>carnivoros<span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="cap03.html#cb12-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(sp_name, sp_pa, value_median, buff_dist_km) <span class="sc">|&gt;</span></span>
<span id="cb12-4"><a href="cap03.html#cb12-4" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">nest</span>(<span class="at">data =</span> <span class="sc">-</span><span class="fu">c</span>(sp_name, buff_dist_km)) <span class="sc">|&gt;</span></span>
<span id="cb12-5"><a href="cap03.html#cb12-5" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb12-6"><a href="cap03.html#cb12-6" tabindex="-1"></a>    <span class="at">fit =</span> <span class="fu">map</span>(data, <span class="sc">~</span> <span class="fu">glm</span>(sp_pa <span class="sc">~</span> value_median, </span>
<span id="cb12-7"><a href="cap03.html#cb12-7" tabindex="-1"></a>                          <span class="at">data =</span> .x, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)),</span>
<span id="cb12-8"><a href="cap03.html#cb12-8" tabindex="-1"></a>    <span class="at">tidied =</span> <span class="fu">map</span>(fit, tidy), </span>
<span id="cb12-9"><a href="cap03.html#cb12-9" tabindex="-1"></a>    <span class="at">glanced =</span> <span class="fu">map</span>(fit, glance)</span>
<span id="cb12-10"><a href="cap03.html#cb12-10" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> modelos_carnivoros</span></code></pre></div>
<p>Models resutls.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="cap03.html#cb13-1" tabindex="-1"></a>modelos_carnivoros <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="cap03.html#cb13-2" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(glanced) <span class="sc">|&gt;</span> </span>
<span id="cb13-3"><a href="cap03.html#cb13-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">dev_exp =</span> (null.deviance <span class="sc">-</span> deviance)<span class="sc">/</span>null.deviance</span>
<span id="cb13-4"><a href="cap03.html#cb13-4" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb13-5"><a href="cap03.html#cb13-5" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(sp_name, buff_dist_km, logLik, null.deviance, deviance, dev_exp, AIC) <span class="sc">|&gt;</span> </span>
<span id="cb13-6"><a href="cap03.html#cb13-6" tabindex="-1"></a>  <span class="fu">left_join</span>(modelos_carnivoros <span class="sc">|&gt;</span> </span>
<span id="cb13-7"><a href="cap03.html#cb13-7" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(tidied) <span class="sc">|&gt;</span> </span>
<span id="cb13-8"><a href="cap03.html#cb13-8" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;value_median&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-9"><a href="cap03.html#cb13-9" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">p.value =</span> <span class="fu">round</span>(p.value,<span class="dv">4</span>) ) <span class="sc">|&gt;</span> </span>
<span id="cb13-10"><a href="cap03.html#cb13-10" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(sp_name, buff_dist_km, term, estimate, p.value) </span>
<span id="cb13-11"><a href="cap03.html#cb13-11" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb13-12"><a href="cap03.html#cb13-12" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(sp_name, <span class="fu">desc</span>(dev_exp))</span></code></pre></div>
<pre><code>## Joining with `by = join_by(sp_name, buff_dist_km)`</code></pre>
<pre><code>## # A tibble: 24 × 10
##    sp_name buff_dist_km logLik null.deviance deviance dev_exp   AIC term        
##    &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       
##  1 sppB           8      -60.5          142.    121.   0.150  125.  value_median
##  2 sppB           4      -61.4          142.    123.   0.137  127.  value_median
##  3 sppB          16      -62.2          142.    124.   0.127  128.  value_median
##  4 sppB           2      -62.4          142.    125.   0.123  129.  value_median
##  5 sppB           1      -64.8          142.    130.   0.0892 134.  value_median
##  6 sppB           0.125  -64.9          142.    130.   0.0886 134.  value_median
##  7 sppB           0.5    -66.4          142.    133.   0.0671 137.  value_median
##  8 sppB           0.25   -67.1          142.    134.   0.0568 138.  value_median
##  9 sppC           4      -41.4          113.     82.8  0.270   86.8 value_median
## 10 sppC           2      -41.7          113.     83.3  0.265   87.3 value_median
## # ℹ 14 more rows
## # ℹ 2 more variables: estimate &lt;dbl&gt;, p.value &lt;dbl&gt;</code></pre>
<p>Plot model results.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="cap03.html#cb16-1" tabindex="-1"></a>modelos_carnivoros <span class="sc">|&gt;</span> </span>
<span id="cb16-2"><a href="cap03.html#cb16-2" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(glanced) <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="cap03.html#cb16-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">dev_exp =</span> (null.deviance <span class="sc">-</span> deviance)<span class="sc">/</span>null.deviance</span>
<span id="cb16-4"><a href="cap03.html#cb16-4" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb16-5"><a href="cap03.html#cb16-5" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(sp_name, buff_dist_km, logLik, null.deviance, deviance, dev_exp, AIC) <span class="sc">|&gt;</span> </span>
<span id="cb16-6"><a href="cap03.html#cb16-6" tabindex="-1"></a>  <span class="fu">left_join</span>(modelos_carnivoros <span class="sc">|&gt;</span> </span>
<span id="cb16-7"><a href="cap03.html#cb16-7" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(tidied) <span class="sc">|&gt;</span> </span>
<span id="cb16-8"><a href="cap03.html#cb16-8" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;value_median&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-9"><a href="cap03.html#cb16-9" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">p.value =</span> <span class="fu">round</span>(p.value,<span class="dv">4</span>) ) <span class="sc">|&gt;</span> </span>
<span id="cb16-10"><a href="cap03.html#cb16-10" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(sp_name, buff_dist_km, term, estimate, p.value) </span>
<span id="cb16-11"><a href="cap03.html#cb16-11" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> model_summary</span></code></pre></div>
<pre><code>## Joining with `by = join_by(sp_name, buff_dist_km)`</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="cap03.html#cb18-1" tabindex="-1"></a>model_summary <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="cap03.html#cb18-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>buff_dist_km, <span class="at">y =</span> AIC)) <span class="sc">+</span> </span>
<span id="cb18-3"><a href="cap03.html#cb18-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb18-4"><a href="cap03.html#cb18-4" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb18-5"><a href="cap03.html#cb18-5" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">10</span>, <span class="dv">12</span>,<span class="dv">14</span>,<span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb18-6"><a href="cap03.html#cb18-6" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sp_name, <span class="at">nrow =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb18-7"><a href="cap03.html#cb18-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;distância (km)&quot;</span>) <span class="ot">-&gt;</span> fig_scale_effect_AIC</span>
<span id="cb18-8"><a href="cap03.html#cb18-8" tabindex="-1"></a></span>
<span id="cb18-9"><a href="cap03.html#cb18-9" tabindex="-1"></a>fig_scale_effect_AIC</span></code></pre></div>
<p><img src="epr_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="cap03.html#cb19-1" tabindex="-1"></a>model_summary  <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="cap03.html#cb19-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>buff_dist_km, <span class="at">y =</span> logLik)) <span class="sc">+</span> </span>
<span id="cb19-3"><a href="cap03.html#cb19-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb19-4"><a href="cap03.html#cb19-4" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb19-5"><a href="cap03.html#cb19-5" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">10</span>, <span class="dv">12</span>,<span class="dv">14</span>,<span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb19-6"><a href="cap03.html#cb19-6" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sp_name, <span class="at">nrow =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb19-7"><a href="cap03.html#cb19-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;distância (km)&quot;</span>, </span>
<span id="cb19-8"><a href="cap03.html#cb19-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;log-verossimilhança&quot;</span>) <span class="ot">-&gt;</span> fig_scale_effect_loglik</span>
<span id="cb19-9"><a href="cap03.html#cb19-9" tabindex="-1"></a></span>
<span id="cb19-10"><a href="cap03.html#cb19-10" tabindex="-1"></a>fig_scale_effect_loglik</span></code></pre></div>
<p><img src="epr_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="cap03.html#cb20-1" tabindex="-1"></a>model_summary  <span class="sc">|&gt;</span> </span>
<span id="cb20-2"><a href="cap03.html#cb20-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>buff_dist_km, <span class="at">y =</span> dev_exp)) <span class="sc">+</span> </span>
<span id="cb20-3"><a href="cap03.html#cb20-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb20-4"><a href="cap03.html#cb20-4" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb20-5"><a href="cap03.html#cb20-5" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">10</span>, <span class="dv">12</span>,<span class="dv">14</span>,<span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb20-6"><a href="cap03.html#cb20-6" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sp_name, <span class="at">nrow =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb20-7"><a href="cap03.html#cb20-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;distância (km)&quot;</span>, </span>
<span id="cb20-8"><a href="cap03.html#cb20-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;variação explicada&quot;</span>) <span class="ot">-&gt;</span> fig_scale_effect_dev</span>
<span id="cb20-9"><a href="cap03.html#cb20-9" tabindex="-1"></a></span>
<span id="cb20-10"><a href="cap03.html#cb20-10" tabindex="-1"></a>fig_scale_effect_dev</span></code></pre></div>
<p><img src="epr_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
<p>No entanto, quando plotamos os parâmetros β dos modelos em diferentes escalas, descobrimos que as relações são idênticas quando a cobertura florestal é medida em 2 km ou em tamanhos de buffer maiores. Apenas em escalas menores (125 a 500 m) vemos uma fraca relação com a cobertura florestal. Essa incerteza quanto à escala do efeito é provavelmente uma consequência da cobertura florestal estar altamente correlacionada entre escalas, como vimos anteriormente. No entanto, há evidências consistentes de que a ocorrência de carnivoros mudar com a cobertura florestal na paisagem, independentemente da escala.</p>
</div>
<div id="pergunta-7-1" class="section level4 hasAnchor" number="3.3.2.3">
<h4><span class="header-section-number">3.3.2.3</span> Pergunta 7<a href="cap03.html#pergunta-7-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><span style=" font-weight: bold;    color: blue !important;">Vimos como a incerteza quanto à escala do efeito é provavelmente, pelo menos em parte, uma consequência da correlação entre escalas. Também é possível que, além da cobertura florestal, existam outros fatores que afetem a ocorrência das espécies na paisagem estudada. Usando como base o conteudo das aulas, leitura disponivel no Google Classroom (Base teórica 4 Dados, métricas, analises), e/ou exemplos apresentados aqui no tutorial, apresentam algumas hipóteses alternativas que poderiam explicar a incerteza nos modelos. Forneça recomendações para variáveis adicionais que poderiam ser incluídas nos modelos para testar suas hipóteses. Justifique sua seleção de forma clara e concisa, apoie sua escolha com exemplos da literatura científica.</span></p>
<hr />
<p>Essa foi a última pergunta. O que se segue é um exemplo que mostra uma abordagem alternativa.</p>
<div style="page-break-after: always;"></div>
</div>
</div>
</div>
<div id="kernels" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Kernels<a href="cap03.html#kernels" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Nesta seção usaremos funções no pacote <span style="     border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: #dedede !important;">siland</span> para executar uma análise de escala de efeito usando Kernels espaciais.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fig-kerneltypes"></span>
<img src="figures/spatialkernels.png" alt="Esquema ilustrativo demonstrando diferentes tipos de kernels espaciais: (A) diagrama representando a estrutura geral de um filtro espacial baseado em kernel; (B) os cinco tipos mais comuns de distribuições espaciais de kernel; (C) núcleos espaciais de largura de banda de distância fixa (estática); e (D) núcleos espaciais de distância adaptativa. Observe que a figura é baseada nas seguintes fontes: Figura 3.4 na página 86 de Bailey e Gatrell (1995); Fotheringham et al. (2002) Figuras 2.11 e 2.13 nas páginas 45 e 47 respectivamente; Figura 3.2 na página 37 de Wang (2006); páginas 67-68 de Smith e Bruce (2008); e Figura 4-47 na página 177 de de Smith et al. (2009)." width="50%" height="50%" />
<p class="caption">
Figura 3.6: Esquema ilustrativo demonstrando diferentes tipos de kernels espaciais: (A) diagrama representando a estrutura geral de um filtro espacial baseado em kernel; (B) os cinco tipos mais comuns de distribuições espaciais de kernel; (C) núcleos espaciais de largura de banda de distância fixa (estática); e (D) núcleos espaciais de distância adaptativa. Observe que a figura é baseada nas seguintes fontes: Figura 3.4 na página 86 de Bailey e Gatrell (1995); Fotheringham et al. (2002) Figuras 2.11 e 2.13 nas páginas 45 e 47 respectivamente; Figura 3.2 na página 37 de Wang (2006); páginas 67-68 de Smith e Bruce (2008); e Figura 4-47 na página 177 de de Smith et al. (2009).
</p>
</div>
<p>A abordagem de Kernels fornece uma maneira rigorosa de estimar as escalas nas quais as variáveis da paisagem afetam respostas ecologicas, e pode ser incorporado na maioria das classes de modelos estatísticos (<span class="citation">Chandler and Hepinstall-Cymerman (2016)</span>). Esta abordagem pode reduzir o viés do modelo e levar a interpretações mais precisas das relações espécie-paisagem <span class="citation">(Aue et al. 2012; Chandler and Hepinstall-Cymerman 2016; Miguet, Fahrig, and Lavigne 2017)</span>. A função de suavização Kernel assume que o efeito de uma variável da paisagem é mais forte perto do local focal e decai em função da distância. Assim fornecendo uma representação mais realista de muitos processos ecológicos como por exemplo, dispersão de sementes <span class="citation">(Bullock et al. 2017)</span> e movimentos de forrageadoras de lugar central (Orians e Pearson 1979).</p>
</div>
<div id="links-uteis" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Links uteis<a href="cap03.html#links-uteis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tidy Modeling with R: <a href="https://www.tmwr.org/" class="uri">https://www.tmwr.org/</a>
models: <a href="https://www.tmwr.org/models" class="uri">https://www.tmwr.org/models</a>
workflow: <a href="https://www.tmwr.org/workflows" class="uri">https://www.tmwr.org/workflows</a></p>
<p>R for Data Science Many Models: <a href="https://r4ds.had.co.nz/many-models.html" class="uri">https://r4ds.had.co.nz/many-models.html</a></p>

</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="cap02.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="garimpo-do-lourenço.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/darrennorris/epr/edit/main/03-especies.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/darrennorris/epr/blob/main/03-especies.Rmd",
"text": null
},
"download": ["epr.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
